name: Create release

on:
release:
types:
- created

jobs:
build:
runs-on: ubuntu-latest

steps:
- name: Zip Folder
run: zip -r ${{ github.event.repository.name }}.zip .

- name: Release
uses: softprops/action-gh-release@v1
if: startsWith(github.ref, 'refs/tags/')
with:
files: ${{ github.event.repository.name }}.zip
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}